// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMVoTRMNB77m4n17y2pRrp6ZsLPigRlbE',
    appId: '1:582634538836:web:0a01e442c25a67012c6ac1',
    messagingSenderId: '582634538836',
    projectId: 'chatapp-91566',
    authDomain: 'chatapp-91566.firebaseapp.com',
    storageBucket: 'chatapp-91566.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeDE0vsVC775GWX23-2S4--XgtQY7A1cc',
    appId: '1:582634538836:android:612b101c750f3bcc2c6ac1',
    messagingSenderId: '582634538836',
    projectId: 'chatapp-91566',
    storageBucket: 'chatapp-91566.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuC4PowDbA3X57V_TQfYk9BZR3zBo3HUY',
    appId: '1:582634538836:ios:7e2c7384c01165ed2c6ac1',
    messagingSenderId: '582634538836',
    projectId: 'chatapp-91566',
    storageBucket: 'chatapp-91566.appspot.com',
    androidClientId: '582634538836-cps31na4ao1j6003640h6traerj8vffb.apps.googleusercontent.com',
    iosClientId: '582634538836-cmd8rbect3s1nd9omvlt63ct2ns4haib.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
